spring:
  zipkin:
    base-url: http://localhost:9411
    enabled: true

  datasource:
    url: jdbc:oracle:thin:@//172.16.3.1:1521/orcl19c
    username: DCBPAYPRO_AUTHMATRIX
    password: DCBPAYPRO_AUTHMATRIX
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.Oracle12cDialect
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true

  sql:
    init:
      mode: never
